# Exercise 1 - Introduction to PyTorch



## Creating and indexing data from tensors

In [ ]:
import torch

In [ ]:
a = torch.tensor([[0., 2., 4.], [3., 5., 7.]])  # shape (2, 3)
b = torch.zeros(3, 3, 3)  # shape (3, 3, 3)
c = torch.linspace(0, 1, 10)  # shape (x)
d = torch.ones(1, 3)  # shape (1, 3)

In [ ]:
print(f"The size of 'a' tensor is: {a.shape}")
print(f"The size of 'b tensor is: {b.shape}")
print(f"The size of 'c' tensor is: {c.shape}")
print(f"The size of 'd' tensor is: {d.shape}")

The size of 'a' tensor is: torch.Size([2, 3])
The size of 'b tensor is: torch.Size([3, 3, 3])
The size of 'c' tensor is: torch.Size([10])
The size of 'd' tensor is: torch.Size([1, 3])


In [ ]:
print(f"The first element of tensor 'a' is: {a[0,0]}")
print(f"The first order tensor along first column of tensor 'a' is: {a[:,0]}")
print(f"The last element of tensor 'a' is: {a[-1, -1]}")
print(f"The first second order tensor [3, 3] of the third order [3, 3, 3] tensor 'b' is: ")
print(f"{b[0, :, :]}")
print(f"The last two elements of the first order tensor along the first row is: {a[0, 1:3]}")

The first element of tensor 'a' is: 0.0
The first order tensor along first column of tensor 'a' is: tensor([0., 3.])
The last element of tensor 'a' is: 7.0
The first second order tensor [3, 3] of the third order [3, 3, 3] tensor 'b' is: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
The last two elements of the first order tensor along the first row is: tensor([2., 4.])


## Tensor Operations

In [ ]:
torch.cat((a, d),0)

tensor([[0., 2., 4.],
        [3., 5., 7.],
        [1., 1., 1.]])

In [ ]:
torch.transpose(a, 0, 1)

tensor([[0., 3.],
        [2., 5.],
        [4., 7.]])

In [ ]:
torch.permute(b, (2, 1, 0))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.reshape(a, (1, 6))

tensor([[0., 2., 4., 3., 5., 7.]])

In [ ]:
torch.unsqueeze(a ,0)

tensor([[[0., 2., 4.],
         [3., 5., 7.]]])

In [ ]:
torch.squeeze(d, 0)

tensor([1., 1., 1.])

In [ ]:
torch.unsqueeze(d, 0).shape # before apply unsqueeze, the size was [1, 3]

torch.Size([1, 1, 3])

In [ ]:
torch.flatten(b)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.])

In [ ]:
torch.ones_like(c)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
torch.cos(a)

tensor([[ 1.0000, -0.4161, -0.6536],
        [-0.9900,  0.2837,  0.7539]])

## Conversion to and from NumPy

In [ ]:
import numpy as np

a = np.array([2., 3.])
b = torch.from_numpy(a)  # convert numpy array to torch tensor
c = b.numpy()  # convert torch tensor from numpy arrary

a == c

array([ True,  True])

## Grid Creation

In [ ]:
x = torch.linspace(0, 1, 10)
y = torch.linspace(0, 2, 5)
x, y = torch.meshgrid(x, y, indexing='ij')

## Gradient Computation

In [ ]:
x.requires_grad = True
y = torch.tensor([0.], requires_grad=True)

In [ ]:
x.data
x.requires_grad
x.grad
x.grad_fn
x.is_leaf

## Example gradients for simple functions

In [ ]:
x = torch.linspace(0., 1., 20, requires_grad=True)
y = 2 * x
z = y ** 2

y.retain_grad()
z.backward(torch.ones_like(z))

dzdx = x.grad
dzdy = y.grad

print(x.grad)

In [ ]:
import matplotlib.pyplot as plt

plt.plot(x.detach(), z.detach(), label='z')
plt.plot(x.detach(), dzdx, '-', label='dz/dx')
plt.plot(x.detach(), dzdy, '-', label='dz/dy')

plt.legend()
plt.grid(True)
plt.show()

## Neural Networks

In [ ]:
model = torch.nn.Linear(2,3)
x = torch.tensor([[1., 2.]])
y = model(x)

model.weight.data
model.bias.data

## GPU Acceleration

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

a = torch.ones(4, device=device)
b = torch.ones(4)

b = b.to(device)
model = model.to(device)

a.cpu()